version: "3.3"

services:
  # MySQL
  db:
    container_name: "db"
    # path配下のDockerfile読み込み
    build: ./docker/mysql
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./docker/mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./log/mysql:/var/log/mysql # ログの保存
    networks:
      - local-net
  # FastAPI
  api:
    # db起動後に立ち上げる
    links:
      - db
    container_name: "api"
    # path配下のDockerfile読み込み
    build: ./docker/api
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/usr/src/server
    env_file: .env
    networks:
      - local-net

  fd:
    build: ./docker/front
    container_name: "front"
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm install react-scripts --save && npm install react && npm install @mui/icons-material @mui/material @emotion/styled @emotion/react @mui/x-charts && npm install axios && npm start"
    ports:
      - "3000:3000"
    links:
      - api
    networks:
      - local-net


# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  local-net:
    driver: bridge